name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  buildpush:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image for production
      run: buildx create --name multi-arch --platform "linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v8" --driver "docker-container" --target production . --tag ${{ secrets.DOCKERHUB_USERNAME }}/flask-mio:prod

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-mio:prod
